name: 02-workflow-events

on: push

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: show te trigger
              run: |
                    echo "Triggering event: ${{ github.event_name }} event"
            
                   
                
                