name: 11-working with inputs

on:
    workflow_dispatch:
        inputs:
            dry-run:
                type: boolean
                description: Skip deployment and only print build outputs
                default: false
            target:
                type: environment
                required: true
                description: which environment the workflow will target
            tag:
                type: choice
                options: 
                    - v1
                    - v2
                    - v3
                default: v3
                description: Release from which to build and deplay

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Build
          run: echo " Building from tag ${{ inputs.tag }}"
    deploy:
        runs-on: ubuntu-latest
        if: ${{ !inputs.dry-run }}
        environment: ${{ inputs.target }}
        needs: build
        steps:
            - name: Deploy
              run: echo "Deploying to  ${{ inputs.target }}"